--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ErikPDev/VoteParty
build-by-default: true
branches:
- main
projects:
  VoteParty:
    path: ""
    icon: "assets/icon.png"
    lint:
      phpstan: false
...
