name: VoteParty
author: ErikPDev
api: 4.0.0
version: 1.4
main: ErikPDev\VoteParty\Main
softdepend:
  - ScoreHud
  - Scoreboard
  - Voting38
commands:
  voteparty:
    description: "Call the VoteParty Event"
    permission: "voteparty.use"
  votepartyreset:
    description: "Reset the VoteParty counter"
    permission: "voteparty.reset"

permissions:
  voteparty.use:
    description: "Permission to use voteparty"
    default: op
  voteparty.reset:
    description: "Permission to use votepartyreset"
    default: op
