name: VoteParty
author: ErikPDev
api: 3.0.0
version: 1.0
main: ErikPDev\VoteParty\Main
commands:
  voteparty:
    description: "Call the VoteParty Event"
    permission: "voteparty.use"

permissions:
  voteparty.use:
    description: "Permission to use voteparty"
    default: op
