 #__      __   _       _____           _         
 #\ \    / /  | |     |  __ \         | |        
 # \ \  / /__ | |_ ___| |__) |_ _ _ __| |_ _   _ 
 #  \ \/ / _ \| __/ _ \  ___/ _` | '__| __| | | |
 #   \  / (_) | ||  __/ |  | (_| | |  | |_| |_| |
 #    \/ \___/ \__\___|_|   \__,_|_|   \__|\__, |
 #                                          __/ |
 #                                         |___/ By @ErikPDev for PMMP
 #
 # VoteParty, a VoteRewardSystem plugin for PocketMine-MP
 # Copyright (c) 2021 ErikPDev  < https://github.com/ErikPDev >
 #
 #
 # This software is distributed under "GNU General Public License v3.0".
 # This license allows you to use it and/or modify it but you are not at
 # all allowed to sell this plugin at any cost. If found doing so the
 # necessary action required would be taken.
 #
 # VoteParty is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License v3.0 for more details.
 #
 # You should have received a copy of the GNU General Public License v3.0
 # along with this program. If not, see
 # <https://opensource.org/licenses/GPL-3.0>.
 # ------------------------------------------------------------------------

# § - Custom color format, Same like minecraft default
# A list of color codes
# | Color Name   | Code |
# |--------------|------|
# | Dark Red     | §4   |
# | Red          | §c   |
# | Gold         | §6   |
# | Yellow       | §e   |
# | Dark Yellow  | §g   |
# | Dark Green   | §2   |
# | Green        | §a   |
# | Aqua         | §b   |
# | Dark Aqua    | §3   |
# | Dark Blue    | §1   |
# | Blue         | §9   |
# | Light Purple | §d   |
# | Dark Purple  | §5   |
# | White        | §f   |
# | Gray         | §7   |
# | Dark Gray    | §8   |
# | Black        | §0   |


CountdownMSG: "§e{number}§f votes remaning till §6s§9u§ar§bp§cr§di§es§3e§9s§c!!" # Message to broadcast when a person voted.
VotestoVoteParty: 10 # How many votes to start the party.
WhenReached: "Partyyy!" # Message to broadcast when countdown reached
ErrorRunning: "This command can only be ran by the console!"
BetterVotingSupport: false # This will add support for BetterVoting and will disable the command, Set to  `true` to use.
PocketVoteSupport: false # This will add support for PocketVote and will disable the command, Set to  `true` to use.
commandtoRun: 
  # They should not include the first "/" and they should be encased in quotes.
  # It is recommended to encase the username variable in escaped quotes (\") to make sure it
  # Selectors:
  #   @a - All Players, this is experimental 
  - "keyall diamond"
  - "give \"@a\" diamond 64"

config-verison: 1 # Please don't change this.